# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
branches:
  only:
  - master
r_build_args: '--resave-data --compact-vignettes="both" '

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
