# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simplify <- function(allnames, allpowers, coefficients) {
    .Call('skimpy_simplify', PACKAGE = 'skimpy', allnames, allpowers, coefficients)
}

mvp_prod <- function(allnames1, allpowers1, coefficients1, allnames2, allpowers2, coefficients2) {
    .Call('skimpy_mvp_prod', PACKAGE = 'skimpy', allnames1, allpowers1, coefficients1, allnames2, allpowers2, coefficients2)
}

mvp_add <- function(allnames1, allpowers1, coefficients1, allnames2, allpowers2, coefficients2) {
    .Call('skimpy_mvp_add', PACKAGE = 'skimpy', allnames1, allpowers1, coefficients1, allnames2, allpowers2, coefficients2)
}

mvp_power <- function(allnames, allpowers, coefficients, n) {
    .Call('skimpy_mvp_power', PACKAGE = 'skimpy', allnames, allpowers, coefficients, n)
}

mvp_deriv <- function(allnames, allpowers, coefficients, v) {
    .Call('skimpy_mvp_deriv', PACKAGE = 'skimpy', allnames, allpowers, coefficients, v)
}

